# Generated by Django 3.1.5 on 2021-01-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userutil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
