# Generated by Django 3.1.5 on 2021-01-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userutil'),
        ('api', '0004_auto_20210112_1150'),
    ]

    operations = [
    ]
