# Generated by Django 3.1.5 on 2021-01-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210112_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
