# Generated by Django 3.1.5 on 2021-01-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20210113_1441'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='order',
        #     name='order_data',
        # ),
        # migrations.AddField(
        #     model_name='order',
        #     name='order_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='order',
        #     name='delivery_time',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='order',
        #     name='payment_method',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
