# Generated by Django 3.1.5 on 2021-01-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210114_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='api.item'),
        ),
        migrations.AlterField(
            model_name='ordertopping',
            name='order_item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_items',
                to='api.orderitem'),
        ),
        migrations.AlterField(
            model_name='ordertopping',
            name='topping',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='toppings',
                to='api.topping'),
        ),
    ]
