# Generated by Django 3.1.5 on 2021-01-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210113_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Order',  # モデル名
            old_name='order_data',   # 変更前
            new_name='order_date'    # 変更後
        )
    ]
