# Generated by Django 3.1.5 on 2021-01-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210114_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertopping',
            name='order_item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_toppings',
                to='api.orderitem'),
        ),
    ]
