version: "3.8"

services:
  auth:
    build: ./python
    image: auth
    container_name: auth
    volumes:
      - ./src:/code
      - ./python/uwsgi/:/etc/uwsgi/
      - ./static:/static
    expose:
      - "8000"
    external_links:
      - db
    networks:
      - common_link

networks:
  common_link:
    external: true
