version: "3.3"

services:
  flask:
    build: ./python
    container_name: flask
    volumes:
      - ./src:/code
      - ./python/uwsgi/:/etc/uwsgi/
    expose:
      - "8000"
    external_links:
      - db
      - nginx

    networks:
      - common_link

networks:
  common_link:
    external: true
